memes/Components/PopularTagsViewComponent.cs
using memes.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data.Entity;
using System.Linq;

namespace memes.Components {
    public class PopularTagsViewComponent : ViewComponent {
        private ITagsRepository repo;

        public PopularTagsViewComponent(ITagsRepository repo) {
            this.repo = repo;
        }

        public IViewComponentResult Invoke() {
            ViewBag.CurrentTag = RouteData?.Values["tag"];

            return View(repo.Tags
                .Include(x => x.PostsRelations)
                .OrderByDescending(x => x.PostsRelations.Count)
                .ThenBy(x => x.Value)
                .Take(50)
                .Select(x => new TopTagVm() {
                    Value = x.Value,
                    Count = x.PostsRelations.Count
                }).ToArray());
        }
    }
}

memes/Controllers/PostsController.cs
using memes.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace memes.Controllers {
    public class PostsController : Controller {
        IPostsRepository postsRepo;
        int pageSize = 10;

        public PostsController(IPostsRepository postsRepo) {
            this.postsRepo = postsRepo;
        }

        public async Task<ViewResult> Index(string tag = "", int page = 1) {
            ViewBag.CurrentTag = RouteData?.Values["tag"];

            IQueryable<Post> query = postsRepo.Posts
                .Include(x => x.TagsRealtions)
                    .ThenInclude(x => x.Tag)
                .Where(x => tag == "" ? true : x.TagsRealtions.Any(y => y.Tag.Value == tag))
                .OrderByDescending(x => x.Id);

            return View(new PostViewModel() {
                Posts = await query
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize)
                    .ToListAsync(),
                CurrentTag = tag,
                PageModel = new PageModel() {
                    CurrentPage = page,
                    PageSize = pageSize,
                    Count = await query.CountAsync()
                }
            });
        }

        public ViewResult New() {
            return View(new Post());
        }

        [HttpPost]
        public async Task<IActionResult> New(Post post) {
            if (ModelState.IsValid) {
                await postsRepo.AddAsync(post);
                return RedirectToAction("Index");
            } else {
                return View();
            }
        }

        public async Task<IActionResult> Single(int id, string slug) {
            Post post = await postsRepo.Posts
                .Include(x => x.TagsRealtions)
                    .ThenInclude(x => x.Tag)
                .SingleOrDefaultAsync(x => x.Id == id && x.SluggedTitle == slug);

            if (post == null)
                return NotFound();

            return View(post);
        }
    }
}

memes/Views/Shared/Footer.cshtml
<footer class="footer">
    <div class="container text-right">
        <small class="text-muted"><i>&copy; 2020 mł</i></small>
    </div>
</footer>

memes/Views/Shared/PostCard.cshtml
@model Post

<div class="card mt-2">
    <div class="post-image-container">
        <a asp-controller="Posts" asp-action="Single" asp-route-id="@Model.Id" asp-route-slug="@Model.SluggedTitle">
            <img src="~/uploads/@Url.Content(Model.ImageName)" alt="@Model.ImageName" />
        </a>
    </div>
    <div class="card-body">
        <h5 class="card-title">@Model.Title</h5>
        <p class="card-text">@Model.Description</p>
    </div>
    @if (Model.TagsRealtions != null) {
        <div class="card-footer">
            @foreach (Tag tag in Model.TagsRealtions.Select(x => x.Tag)) {
                <a asp-controller="Posts" asp-action="Index" asp-route-tag="@tag.Value" asp-route-page="@null"><small class="@(ViewBag.CurrentTag == tag.Value ? "font-weight-bold" : "")">@tag.Value</small></a>
            }
        </div>
    }
</div>

memes/Views/Shared/TopNavbar.cshtml
<div class="d-flex flex-column flex-md-row align-items-center justify-content-between p-3 px-md-4 mb-3 bg-white border-bottom border-right border-left box-shadow rounded-bottom">
    <div>
        <h2 class="mb-0">
            <a asp-controller="Posts" asp-action="Index" asp-route-tag="@null" asp-route-page="@null">asdf-memes</a>
        </h2>
        <small><i>site with <del>cats</del> images</i></small>
    </div>

    <nav class="my-2 my-md-0 mr-md-3">
        <a asp-action="New" class="p-2 text-dark">post img</a>
        <a class="p-2" href="#"><b>sign up</b></a>
    </nav>
</div>

memes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="@Url.Content("~/styles.css")" />
    <meta name="viewport" content="width=device-width" />
    <title>asdf-memes</title>
</head>
<body class="bg-light">
    <div class="container">
        @await Html.PartialAsync("TopNavbar")
        <div class="row d-flex justify-content-center">
            <div class="col-md-8 col-sm-12">
                @RenderBody()
            </div>
            <div class="col-md-4 col-sm-12">
                @await Component.InvokeAsync("PopularTags")
            </div>
        </div>
    </div>
    @await Html.PartialAsync("Footer")
</body>
</html>